global:
  cloudProvider:
    dockerRegistryUrl: acrarolibotnonprod.azurecr.io
    flavor: openshift
    imagePullSecretName: mapcolonies-secret
  tracing: {}
  metrics: {}
  environment: production
  imagePullPolicy: IfNotPresent
  filebeat:
    enabled: false
    image: docker.elastic.co/beats/filebeat:7.12.1
    mountPath: /usr/src/app/logs
    pycsw:
      mountPath: /var/log/pycsw
      logFile: pycsw.log
    nginxS3Gateway: 
      mountPath: /var/log/nginx
    elastic:
      host: 10.8.0.8
      port: 9200
      protocol: http
      username: 
      password:
      index: 3d
      sslEnabled: false
    kibana:
      host: 10.8.0.8:5601
 